apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: frontend
  name: frontend
  namespace: inference-lab
spec:
  replicas: 1
  selector:
    matchLabels:
      app: frontend
  strategy: {}
  template:
    metadata:
      labels:
        app: frontend
    spec:
      containers:
      - image: ivantan67/inference-gateway-lab-frontend:latest
        name: frontend
        ports:
        - containerPort: 3000
        env:
        - name: GATEWAY_BASE_URL
          valueFrom:
            configMapKeyRef:
              name: frontend-config
              key: GATEWAY_BACKEND_SVC
        - name: GATEWAY_MODEL 
          valueFrom:
            configMapKeyRef:
              name: frontend-config
              key: GATEWAY_MODEL